/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import avance.poo.*;
/**
 *
 * @author Mara Rivera
 */
public class VAdministrador extends javax.swing.JFrame {
    private GestionAdmin gestionAdmin;
    private GestionCajero gestionCajero;
    private Administrador administrador;
    /**
     * Creates new form VAdministrador
     */
    public VAdministrador() {
        initComponents();
        
        gestionAdmin = new GestionAdmin();
        gestionCajero = new GestionCajero(gestionAdmin);
        DatosPrueba.cargar(gestionAdmin, gestionCajero);

        Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(11111111);

        if (empleado instanceof Administrador) {
            administrador = (Administrador) empleado;
            textoAdministrador.setText("Administrador: " + administrador.getNombreCompleto());
        }

        setLocationRelativeTo(null);
        AreaDeResultados.setText("");
    }
    
    
    public VAdministrador(GestionAdmin gestionAdmin, GestionCajero gestionCajero, Administrador administrador) {
    initComponents();

        this.gestionAdmin = gestionAdmin;
        this.gestionCajero = gestionCajero;
        this.administrador = administrador;

        setLocationRelativeTo(null);
        textoAdministrador.setText("Administrador: " + administrador.getNombreCompleto());
        AreaDeResultados.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        textoAdministrador = new javax.swing.JLabel();
        tituloEmpleados = new javax.swing.JLabel();
        textoDniEmpleado = new javax.swing.JLabel();
        cajaDniEmpleado = new javax.swing.JTextField();
        textoNombresEmpleado = new javax.swing.JLabel();
        cajaNombresEmpleado = new javax.swing.JTextField();
        textoApellidosEmpleado = new javax.swing.JLabel();
        cajaApellidosEmpleado = new javax.swing.JTextField();
        textoPasswordEmpleado = new javax.swing.JLabel();
        cajaPasswordEmpleado = new javax.swing.JTextField();
        textoRolEmpleado = new javax.swing.JLabel();
        cajaRolEmpleado = new javax.swing.JTextField();
        botonRegistrarEmpleado = new javax.swing.JButton();
        botonBuscarEmpleado = new javax.swing.JButton();
        botonModificarEmpleado = new javax.swing.JButton();
        botonEliminarEmpleado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tituloProductos = new javax.swing.JLabel();
        textoCodigoProducto = new javax.swing.JLabel();
        cajaCodigoProducto = new javax.swing.JTextField();
        textoNombreProducto = new javax.swing.JLabel();
        cajaNombreProducto = new javax.swing.JTextField();
        textoPrecioProducto = new javax.swing.JLabel();
        cajaPrecioProducto = new javax.swing.JTextField();
        textoCategoriaProducto = new javax.swing.JLabel();
        checkHamburguesa = new javax.swing.JCheckBox();
        checkBebida = new javax.swing.JCheckBox();
        checkAcompanamiento = new javax.swing.JCheckBox();
        textoStockProducto = new javax.swing.JLabel();
        cajaStockProducto = new javax.swing.JTextField();
        botonBuscarProducto = new javax.swing.JButton();
        botonModificarProducto = new javax.swing.JButton();
        botonEliminarProducto = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        tituloCombos = new javax.swing.JLabel();
        textoCodigoCombo = new javax.swing.JLabel();
        cajaCodigoCombo = new javax.swing.JTextField();
        textoNombreCombo = new javax.swing.JLabel();
        cajaNombreCombo = new javax.swing.JTextField();
        textoPrecioCombo = new javax.swing.JLabel();
        cajaPrecioCombo = new javax.swing.JTextField();
        botonRegistrarCombo = new javax.swing.JButton();
        botonBuscarCombo = new javax.swing.JButton();
        botonModificarCombo = new javax.swing.JButton();
        botonEliminarCombo = new javax.swing.JButton();
        tituloProductoCombo = new javax.swing.JLabel();
        textoComboAgregar = new javax.swing.JLabel();
        cajaComboAgregar = new javax.swing.JTextField();
        textoProductoAgregar = new javax.swing.JLabel();
        cajaProductoAgregar = new javax.swing.JTextField();
        botonAgregarProductoCombo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        tituloReportes = new javax.swing.JLabel();
        botonReporteProductividad = new javax.swing.JButton();
        botonReporteIngresos = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        tituloResultado = new javax.swing.JLabel();
        jScrollPaneResultado = new javax.swing.JScrollPane();
        jSeparator7 = new javax.swing.JSeparator();
        areaResultado = new javax.swing.JScrollPane();
        AreaDeResultados = new javax.swing.JTextArea();
        botonRegistrarProducto = new javax.swing.JButton();
        botonVerEmpleados = new javax.swing.JButton();
        botonVerProductos = new javax.swing.JButton();
        botonVerCombos = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Buen día Administrador!");

        textoAdministrador.setText("Administrador:");

        tituloEmpleados.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloEmpleados.setText("Gestión de Empleados");

        textoDniEmpleado.setText("DNI:");

        textoNombresEmpleado.setText("Nombres:");

        textoApellidosEmpleado.setText("Apellidos:");

        textoPasswordEmpleado.setText("Contraseña:");

        textoRolEmpleado.setText("Rol:");

        botonRegistrarEmpleado.setText("REGISTRAR");
        botonRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEmpleadoActionPerformed(evt);
            }
        });

        botonBuscarEmpleado.setText("BUSCAR");
        botonBuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarEmpleadoActionPerformed(evt);
            }
        });

        botonModificarEmpleado.setText("MODIFICAR");
        botonModificarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEmpleadoActionPerformed(evt);
            }
        });

        botonEliminarEmpleado.setText("ELIMINAR");
        botonEliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpleadoActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tituloProductos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloProductos.setText("Gestión de productos");

        textoCodigoProducto.setText("Código:");

        textoNombreProducto.setText("Nombre:");

        textoPrecioProducto.setText("Precio:");

        textoCategoriaProducto.setText("Categoría:");

        checkHamburguesa.setText("Hamburguesa");
        checkHamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkHamburguesaActionPerformed(evt);
            }
        });

        checkBebida.setText("Bebida");
        checkBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBebidaActionPerformed(evt);
            }
        });

        checkAcompanamiento.setText("Acompañamiento");
        checkAcompanamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAcompanamientoActionPerformed(evt);
            }
        });

        textoStockProducto.setText("Stock:");

        botonBuscarProducto.setText("BUSCAR");
        botonBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarProductoActionPerformed(evt);
            }
        });

        botonModificarProducto.setText("MODIFICAR");
        botonModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProductoActionPerformed(evt);
            }
        });

        botonEliminarProducto.setText("ELIMINAR");
        botonEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProductoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tituloCombos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloCombos.setText("Gestión de Combos");

        textoCodigoCombo.setText("Código combo:");

        textoNombreCombo.setText("Nombre combo:");

        textoPrecioCombo.setText("Precio Promocional:");

        botonRegistrarCombo.setText("REGISTRAR");
        botonRegistrarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarComboActionPerformed(evt);
            }
        });

        botonBuscarCombo.setText("BUSCAR");
        botonBuscarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarComboActionPerformed(evt);
            }
        });

        botonModificarCombo.setText("MODIFICAR");
        botonModificarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarComboActionPerformed(evt);
            }
        });

        botonEliminarCombo.setText("ELIMINAR");
        botonEliminarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarComboActionPerformed(evt);
            }
        });

        tituloProductoCombo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tituloProductoCombo.setText("Agregar producto al combo:");

        textoComboAgregar.setText("Código combo:");

        textoProductoAgregar.setText("Código producto:");

        botonAgregarProductoCombo.setText("AGREGAR");
        botonAgregarProductoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProductoComboActionPerformed(evt);
            }
        });

        tituloReportes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloReportes.setText("Reportes:");

        botonReporteProductividad.setText("REPORTE DE PRODUCTIVIDAD");
        botonReporteProductividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteProductividadActionPerformed(evt);
            }
        });

        botonReporteIngresos.setText("REPORTE DE INGRESOS");
        botonReporteIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteIngresosActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tituloResultado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloResultado.setText("Resultados:");

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AreaDeResultados.setColumns(20);
        AreaDeResultados.setRows(5);
        areaResultado.setViewportView(AreaDeResultados);

        botonRegistrarProducto.setText("REGISTRAR");
        botonRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarProductoActionPerformed(evt);
            }
        });

        botonVerEmpleados.setText("VER EMPLEADOS");
        botonVerEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerEmpleadosActionPerformed(evt);
            }
        });

        botonVerProductos.setText("VER PRODUCTOS");
        botonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerProductosActionPerformed(evt);
            }
        });

        botonVerCombos.setText("VER COMBOS");
        botonVerCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerCombosActionPerformed(evt);
            }
        });

        botonCerrarSesion.setText("CERRAR SESIÓN");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonReporteIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReporteProductividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoDniEmpleado)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tituloEmpleados))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(cajaDniEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoApellidosEmpleado)
                            .addComponent(textoNombresEmpleado)
                            .addComponent(textoPasswordEmpleado)
                            .addComponent(textoRolEmpleado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaNombresEmpleado)
                            .addComponent(cajaApellidosEmpleado)
                            .addComponent(cajaPasswordEmpleado)
                            .addComponent(cajaRolEmpleado)))
                    .addComponent(botonRegistrarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonBuscarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEliminarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCodigoProducto)
                                    .addComponent(textoNombreProducto)
                                    .addComponent(textoPrecioProducto)
                                    .addComponent(textoCategoriaProducto)
                                    .addComponent(textoStockProducto))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cajaCodigoProducto)
                                            .addComponent(cajaNombreProducto)
                                            .addComponent(cajaPrecioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(checkHamburguesa)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkBebida))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(checkAcompanamiento))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cajaStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(tituloProductos))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonVerEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botonBuscarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonModificarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                        .addComponent(botonEliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator3)
                                        .addComponent(botonRegistrarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(tituloCombos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(tituloProductoCombo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(botonVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(botonAgregarProductoCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonRegistrarCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textoNombreCombo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textoCodigoCombo)
                                                    .addComponent(textoPrecioCombo))
                                                .addGap(32, 32, 32)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cajaPrecioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cajaNombreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cajaCodigoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textoComboAgregar)
                                                    .addComponent(textoProductoAgregar))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cajaComboAgregar)
                                                    .addComponent(cajaProductoAgregar)))
                                            .addComponent(botonBuscarCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonModificarCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonEliminarCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(botonVerCombos, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(areaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(tituloReportes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(textoAdministrador)
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloResultado)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textoAdministrador)
                            .addComponent(botonCerrarSesion))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(tituloProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoCodigoProducto)
                                    .addComponent(cajaCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoNombreProducto)
                                    .addComponent(cajaNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoPrecioProducto)
                                    .addComponent(cajaPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoCategoriaProducto)
                                    .addComponent(checkHamburguesa)
                                    .addComponent(checkBebida))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkAcompanamiento)
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoStockProducto)
                                    .addComponent(cajaStockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonRegistrarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBuscarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonModificarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEliminarProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloEmpleados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoDniEmpleado)
                                    .addComponent(cajaDniEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoNombresEmpleado)
                                    .addComponent(cajaNombresEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoApellidosEmpleado)
                                    .addComponent(cajaApellidosEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoPasswordEmpleado)
                                    .addComponent(cajaPasswordEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoRolEmpleado)
                                    .addComponent(cajaRolEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(botonRegistrarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBuscarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonModificarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEliminarEmpleado))
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tituloReportes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonReporteProductividad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonReporteIngresos)
                                        .addContainerGap(41, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jSeparator6)
                                        .addGap(22, 22, 22))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(botonVerEmpleados)
                                    .addComponent(botonVerProductos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonVerCombos)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tituloResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(areaResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(tituloCombos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigoCombo)
                    .addComponent(cajaCodigoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNombreCombo)
                            .addComponent(cajaNombreCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoPrecioCombo)
                            .addComponent(cajaPrecioCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRegistrarCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBuscarCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tituloProductoCombo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoComboAgregar)
                            .addComponent(cajaComboAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoProductoAgregar)
                            .addComponent(cajaProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(botonAgregarProductoCombo)
                        .addContainerGap(166, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarProductoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProductoComboActionPerformed
        // TODO add your handling code here:
        String codigoCombo = cajaComboAgregar.getText();
        String codigoProducto = cajaProductoAgregar.getText();

        if (codigoCombo.equals("") || codigoProducto.equals("")) {
            AreaDeResultados.setText("Ingrese codigo del combo y codigo del producto.");
        } else {
            Combo combo = gestionAdmin.buscarComboPorCodigo(codigoCombo);
            Producto producto = gestionAdmin.buscarProductoPorCodigo(codigoProducto);

            if (combo == null) {
                AreaDeResultados.setText("Combo no encontrado.");
            } else if (producto == null) {
                AreaDeResultados.setText("Producto no encontrado.");
            } else {
                gestionAdmin.agregarProductoACombo(codigoCombo, codigoProducto);
                AreaDeResultados.setText("Producto agregado al combo correctamente.");
            }
        }
    }//GEN-LAST:event_botonAgregarProductoComboActionPerformed

    private void checkHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkHamburguesaActionPerformed
        // TODO add your handling code here:
        if (checkHamburguesa.isSelected()) {
        checkBebida.setSelected(false);
        checkAcompanamiento.setSelected(false);
        }
    }//GEN-LAST:event_checkHamburguesaActionPerformed

    private void checkBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBebidaActionPerformed
        // TODO add your handling code here:
        if (checkBebida.isSelected()) {
        checkHamburguesa.setSelected(false);
        checkAcompanamiento.setSelected(false);
        }
    }//GEN-LAST:event_checkBebidaActionPerformed

    private void checkAcompanamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAcompanamientoActionPerformed
        // TODO add your handling code here:
        if (checkAcompanamiento.isSelected()) {
        checkHamburguesa.setSelected(false);
        checkBebida.setSelected(false);
        }   
    }//GEN-LAST:event_checkAcompanamientoActionPerformed

    private void botonRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEmpleadoActionPerformed
        // TODO add your handling code here:
        String dniTexto = cajaDniEmpleado.getText();
        String nombres = cajaNombresEmpleado.getText();
        String apellidos = cajaApellidosEmpleado.getText();
        String password = cajaPasswordEmpleado.getText();
        String rol = cajaRolEmpleado.getText();

        if (dniTexto.equals("") || nombres.equals("") || apellidos.equals("") || password.equals("") || rol.equals("")) {
            AreaDeResultados.setText("Complete todos los datos del empleado.");
        } else if (!rol.equals("Administrador") && !rol.equals("Cajero") && !rol.equals("Repartidor")) {
            AreaDeResultados.setText("Rol incorrecto.\nUse: Administrador, Cajero o Repartidor.");
        } else {
            int dni = 0;

            for (int i = 0; i < dniTexto.length(); i++) {
                dni = dni * 10 + (dniTexto.charAt(i) - '0');
            }

            Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(dni);

            if (empleado != null) {
                AreaDeResultados.setText("Ya existe un empleado con ese DNI.");
            } else {
                gestionAdmin.registrarEmpleado(dni, nombres, apellidos, password, rol, gestionCajero);

                AreaDeResultados.setText("Empleado registrado correctamente.\n"
                        + "DNI: " + dni + "\n"
                        + "Nombre: " + nombres + " " + apellidos + "\n"
                        + "Rol: " + rol);
            }
        }
    }//GEN-LAST:event_botonRegistrarEmpleadoActionPerformed

    private void botonBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarEmpleadoActionPerformed
        // TODO add your handling code here:                                                 
        String dniTexto = cajaDniEmpleado.getText();

        if (dniTexto.equals("")) {
            AreaDeResultados.setText("Ingrese el DNI del empleado.");
        } else {
            int dni = 0;

            for (int i = 0; i < dniTexto.length(); i++) {
                dni = dni * 10 + (dniTexto.charAt(i) - '0');
            }

            Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(dni);

            if (empleado == null) {
                AreaDeResultados.setText("Empleado no encontrado.");
            } else {
                cajaDniEmpleado.setText(empleado.getDni() + "");
                cajaNombresEmpleado.setText(empleado.getNombres());
                cajaApellidosEmpleado.setText(empleado.getApellidos());
                cajaPasswordEmpleado.setText(empleado.getPassword());
                cajaRolEmpleado.setText(empleado.getRol());

                AreaDeResultados.setText("Empleado encontrado:\n" + empleado.mostrarDatos());
            }
        }
    }//GEN-LAST:event_botonBuscarEmpleadoActionPerformed

    private void botonModificarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEmpleadoActionPerformed
        // TODO add your handling code here:
        String dniTexto = cajaDniEmpleado.getText();
    String nombres = cajaNombresEmpleado.getText();
    String apellidos = cajaApellidosEmpleado.getText();
    String password = cajaPasswordEmpleado.getText();
    String rol = cajaRolEmpleado.getText();

    if (dniTexto.equals("")) {
        AreaDeResultados.setText("Ingrese el DNI del empleado.");
    } else {
        int dni = 0;

        for (int i = 0; i < dniTexto.length(); i++) {
            dni = dni * 10 + (dniTexto.charAt(i) - '0');
        }

        Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(dni);

        if (empleado == null) {
            AreaDeResultados.setText("Empleado no encontrado.");
        } else {
            empleado.setNombres(nombres);
            empleado.setApellidos(apellidos);
            empleado.setPassword(password);
            empleado.setRol(rol);

            AreaDeResultados.setText("Empleado modificado correctamente.");
        }
    }
    }//GEN-LAST:event_botonModificarEmpleadoActionPerformed

    private void botonEliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpleadoActionPerformed
        // TODO add your handling code here:
        String dniTexto = cajaDniEmpleado.getText();

        if (dniTexto.equals("")) {
            AreaDeResultados.setText("Ingrese el DNI del empleado.");
        } else {
            int dni = 0;

            for (int i = 0; i < dniTexto.length(); i++) {
                dni = dni * 10 + (dniTexto.charAt(i) - '0');
            }

            Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(dni);

            if (empleado == null) {
                AreaDeResultados.setText("Empleado no encontrado.");
            } else {
                gestionAdmin.eliminarEmpleado(dni);
                AreaDeResultados.setText("Empleado eliminado correctamente.");
            }
        }
    }//GEN-LAST:event_botonEliminarEmpleadoActionPerformed

    private void botonRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarProductoActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoProducto.getText();
        String nombre = cajaNombreProducto.getText();
        String precioTexto = cajaPrecioProducto.getText();
        String stockTexto = cajaStockProducto.getText();
        String categoria = "";

        if (checkHamburguesa.isSelected()) {
            categoria = "Hamburguesas";
        } else if (checkBebida.isSelected()) {
            categoria = "Bebidas";
        } else if (checkAcompanamiento.isSelected()) {
            categoria = "Acompaniamientos";
        }

        if (codigo.equals("") || nombre.equals("") || precioTexto.equals("") || stockTexto.equals("")) {
            AreaDeResultados.setText("Complete todos los datos del producto.");
        } else if (categoria.equals("")) {
            AreaDeResultados.setText("Seleccione una categoria.");
        } else {
            Producto producto = gestionAdmin.buscarProductoPorCodigo(codigo);

            if (producto != null) {
                AreaDeResultados.setText("Ya existe un producto con ese codigo.");
            } else {
                int precio = 0;
                int stock = 0;

                for (int i = 0; i < precioTexto.length(); i++) {
                    precio = precio * 10 + (precioTexto.charAt(i) - '0');
                }

                for (int i = 0; i < stockTexto.length(); i++) {
                    stock = stock * 10 + (stockTexto.charAt(i) - '0');
                }

                gestionAdmin.registrarProducto(codigo, nombre, precio, categoria, stock);

                AreaDeResultados.setText("Producto registrado correctamente.");
            }
        }
    }//GEN-LAST:event_botonRegistrarProductoActionPerformed

    private void botonBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarProductoActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoProducto.getText();

        if (codigo.equals("")) {
            AreaDeResultados.setText("Ingrese el codigo del producto.");
        } else {
            Producto producto = gestionAdmin.buscarProductoPorCodigo(codigo);

            if (producto == null) {
                AreaDeResultados.setText("Producto no encontrado.");
            } else {
                cajaCodigoProducto.setText(producto.getCodigo());
                cajaNombreProducto.setText(producto.getNombre());
                cajaPrecioProducto.setText(producto.getPrecioBase() + "");
                cajaStockProducto.setText(producto.getStockDisponible() + "");

                checkHamburguesa.setSelected(false);
                checkBebida.setSelected(false);
                checkAcompanamiento.setSelected(false);

                if (producto.getCategoria().equals("Hamburguesas")) {
                    checkHamburguesa.setSelected(true);
                } else if (producto.getCategoria().equals("Bebidas")) {
                    checkBebida.setSelected(true);
                } else if (producto.getCategoria().equals("Acompaniamientos")) {
                    checkAcompanamiento.setSelected(true);
                }

                AreaDeResultados.setText("Producto encontrado:\n" + producto.mostrarDatos());
            }
        }
    }//GEN-LAST:event_botonBuscarProductoActionPerformed

    private void botonModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProductoActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoProducto.getText();
        String nombre = cajaNombreProducto.getText();
        String precioTexto = cajaPrecioProducto.getText();
        String stockTexto = cajaStockProducto.getText();
        String categoria = "";

        if (checkHamburguesa.isSelected()) {
            categoria = "Hamburguesas";
        } else if (checkBebida.isSelected()) {
            categoria = "Bebidas";
        } else if (checkAcompanamiento.isSelected()) {
            categoria = "Acompaniamientos";
        }

        if (codigo.equals("") || nombre.equals("") || precioTexto.equals("") || stockTexto.equals("")) {
            AreaDeResultados.setText("Complete todos los datos del producto.");
        } else if (categoria.equals("")) {
            AreaDeResultados.setText("Seleccione una categoria.");
        } else {
            Producto producto = gestionAdmin.buscarProductoPorCodigo(codigo);

            if (producto == null) {
                AreaDeResultados.setText("Producto no encontrado.");
            } else {
                int precio = 0;
                int stock = 0;

                for (int i = 0; i < precioTexto.length(); i++) {
                    precio = precio * 10 + (precioTexto.charAt(i) - '0');
                }

                for (int i = 0; i < stockTexto.length(); i++) {
                    stock = stock * 10 + (stockTexto.charAt(i) - '0');
                }

                gestionAdmin.modificarProducto(codigo, nombre, precio, categoria, stock);

                AreaDeResultados.setText("Producto modificado correctamente.");
            }
        }
    }//GEN-LAST:event_botonModificarProductoActionPerformed

    private void botonEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProductoActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoProducto.getText();

        if (codigo.equals("")) {
            AreaDeResultados.setText("Ingrese el codigo del producto.");
        } else {
            Producto producto = gestionAdmin.buscarProductoPorCodigo(codigo);

            if (producto == null) {
                AreaDeResultados.setText("Producto no encontrado.");
            } else {
                gestionAdmin.eliminarProducto(codigo);
                AreaDeResultados.setText("Producto eliminado correctamente.");
            }
        }
    }//GEN-LAST:event_botonEliminarProductoActionPerformed

    private void botonRegistrarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarComboActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoCombo.getText();
        String nombre = cajaNombreCombo.getText();
        String precioTexto = cajaPrecioCombo.getText();

        if (codigo.equals("") || nombre.equals("") || precioTexto.equals("")) {
            AreaDeResultados.setText("Complete todos los datos del combo.");
        } else {
            Combo combo = gestionAdmin.buscarComboPorCodigo(codigo);

            if (combo != null) {
                AreaDeResultados.setText("Ya existe un combo con ese codigo.");
            } else {
                int precio = 0;

                for (int i = 0; i < precioTexto.length(); i++) {
                    precio = precio * 10 + (precioTexto.charAt(i) - '0');
                }

                gestionAdmin.registrarCombo(codigo, nombre, precio);

                AreaDeResultados.setText("Combo registrado correctamente.");
            }
        }
    }//GEN-LAST:event_botonRegistrarComboActionPerformed

    private void botonBuscarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarComboActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoCombo.getText();

        if (codigo.equals("")) {
            AreaDeResultados.setText("Ingrese el codigo del combo.");
        } else {
            Combo combo = gestionAdmin.buscarComboPorCodigo(codigo);

            if (combo == null) {
                AreaDeResultados.setText("Combo no encontrado.");
            } else {
                cajaCodigoCombo.setText(combo.getCodigo());
                cajaNombreCombo.setText(combo.getNombre());
                cajaPrecioCombo.setText(combo.getPrecioPromocional() + "");

                AreaDeResultados.setText("Combo encontrado:\n" + combo.mostrarDatos());
            }
        }
    }//GEN-LAST:event_botonBuscarComboActionPerformed

    private void botonModificarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarComboActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoCombo.getText();
        String nombre = cajaNombreCombo.getText();
        String precioTexto = cajaPrecioCombo.getText();

        if (codigo.equals("") || nombre.equals("") || precioTexto.equals("")) {
            AreaDeResultados.setText("Complete todos los datos del combo.");
        } else {
            Combo combo = gestionAdmin.buscarComboPorCodigo(codigo);

            if (combo == null) {
                AreaDeResultados.setText("Combo no encontrado.");
            } else {
                int precio = 0;

                for (int i = 0; i < precioTexto.length(); i++) {
                    precio = precio * 10 + (precioTexto.charAt(i) - '0');
                }

                gestionAdmin.modificarCombo(codigo, nombre, precio);

                AreaDeResultados.setText("Combo modificado correctamente.");
            }
        }
    }//GEN-LAST:event_botonModificarComboActionPerformed

    private void botonEliminarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarComboActionPerformed
        // TODO add your handling code here:
        String codigo = cajaCodigoCombo.getText();

        if (codigo.equals("")) {
            AreaDeResultados.setText("Ingrese el codigo del combo.");
        } else {
            Combo combo = gestionAdmin.buscarComboPorCodigo(codigo);

            if (combo == null) {
                AreaDeResultados.setText("Combo no encontrado.");
            } else {
                gestionAdmin.eliminarCombo(codigo);
                AreaDeResultados.setText("Combo eliminado correctamente.");
            }
        }
    }//GEN-LAST:event_botonEliminarComboActionPerformed

    private void botonVerEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerEmpleadosActionPerformed
        // TODO add your handling code here:
        String texto = "LISTA DE EMPLEADOS\n\n";

        for (int i = 0; i < gestionAdmin.getContadorEmpleados(); i++) {
            Empleado empleado = gestionAdmin.getListaEmpleados()[i];

            texto = texto + empleado.mostrarDatos()  
                    + "\n--------------"
                    + "\n";
        }

        AreaDeResultados.setText(texto);
    }//GEN-LAST:event_botonVerEmpleadosActionPerformed

    private void botonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerProductosActionPerformed
        // TODO add your handling code here:
        String texto = "LISTA DE PRODUCTOS\n\n";

        for (int i = 0; i < gestionAdmin.getContadorProductos(); i++) {
            Producto producto = gestionAdmin.getListaProductos()[i];

            texto = texto + "PRODUCTO " + (i + 1) + "\n";
            texto = texto + "Codigo: " + producto.getCodigo() + "\n";
            texto = texto + "Nombre: " + producto.getNombre() + "\n";
            texto = texto + "Precio: S/" + producto.getPrecioBase() + "\n";
            texto = texto + "Categoria: " + producto.getCategoria() + "\n";
            texto = texto + "Stock: " + producto.getStockDisponible() + "\n";
            texto = texto + "-----------------------------\n\n";
        }

        AreaDeResultados.setText(texto);

        
    }//GEN-LAST:event_botonVerProductosActionPerformed

    private void botonVerCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerCombosActionPerformed
        // TODO add your handling code here:
        String texto = "LISTA DE COMBOS\n\n";

        for (int i = 0; i < gestionAdmin.getContadorCombos(); i++) {
            Combo combo = gestionAdmin.getListaCombos()[i];

            texto = texto + combo.mostrarDatos() + "\n----------"+ "\n";
        }

        AreaDeResultados.setText(texto);
    }//GEN-LAST:event_botonVerCombosActionPerformed

    private void botonReporteProductividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteProductividadActionPerformed
        // TODO add your handling code here:
        String texto = "REPORTE DE PRODUCTIVIDAD\n\n";

        for (int i = 0; i < gestionAdmin.getContadorEmpleados(); i++) {
            Empleado empleado = gestionAdmin.getListaEmpleados()[i];

            texto = texto + empleado.getNombreCompleto()
                    + "\nRol: " + empleado.getRol()
                    + "\nPedidos atendidos: " + empleado.getPedidosAtendidos() 
                    +"\n---------------------" 
                    +"\n";
        }

        AreaDeResultados.setText(texto);
    }//GEN-LAST:event_botonReporteProductividadActionPerformed

    private void botonReporteIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteIngresosActionPerformed
        // TODO add your handling code here:
        String texto = "REPORTE DE INGRESOS\n\n";
        double total = 0;

        for (int i = 0; i < gestionCajero.getContadorPedidos(); i++) {
            Pedido pedido = gestionCajero.getListaPedidos()[i];

            texto = texto + "Pedido " + pedido.getNumeroCorrelativo()
                    + " | Estado: " + pedido.getEstado()
                    + " | Total: S/" + pedido.calcularTotal() + "\n";

            total = total + pedido.calcularTotal();
        }

        texto = texto + "\nTOTAL: S/" + total;

        AreaDeResultados.setText(texto);
    }//GEN-LAST:event_botonReporteIngresosActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
        VLogin ventana = new VLogin(gestionAdmin, gestionCajero);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaDeResultados;
    private javax.swing.JScrollPane areaResultado;
    private javax.swing.JButton botonAgregarProductoCombo;
    private javax.swing.JButton botonBuscarCombo;
    private javax.swing.JButton botonBuscarEmpleado;
    private javax.swing.JButton botonBuscarProducto;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonEliminarCombo;
    private javax.swing.JButton botonEliminarEmpleado;
    private javax.swing.JButton botonEliminarProducto;
    private javax.swing.JButton botonModificarCombo;
    private javax.swing.JButton botonModificarEmpleado;
    private javax.swing.JButton botonModificarProducto;
    private javax.swing.JButton botonRegistrarCombo;
    private javax.swing.JButton botonRegistrarEmpleado;
    private javax.swing.JButton botonRegistrarProducto;
    private javax.swing.JButton botonReporteIngresos;
    private javax.swing.JButton botonReporteProductividad;
    private javax.swing.JButton botonVerCombos;
    private javax.swing.JButton botonVerEmpleados;
    private javax.swing.JButton botonVerProductos;
    private javax.swing.JTextField cajaApellidosEmpleado;
    private javax.swing.JTextField cajaCodigoCombo;
    private javax.swing.JTextField cajaCodigoProducto;
    private javax.swing.JTextField cajaComboAgregar;
    private javax.swing.JTextField cajaDniEmpleado;
    private javax.swing.JTextField cajaNombreCombo;
    private javax.swing.JTextField cajaNombreProducto;
    private javax.swing.JTextField cajaNombresEmpleado;
    private javax.swing.JTextField cajaPasswordEmpleado;
    private javax.swing.JTextField cajaPrecioCombo;
    private javax.swing.JTextField cajaPrecioProducto;
    private javax.swing.JTextField cajaProductoAgregar;
    private javax.swing.JTextField cajaRolEmpleado;
    private javax.swing.JTextField cajaStockProducto;
    private javax.swing.JCheckBox checkAcompanamiento;
    private javax.swing.JCheckBox checkBebida;
    private javax.swing.JCheckBox checkHamburguesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneResultado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel textoAdministrador;
    private javax.swing.JLabel textoApellidosEmpleado;
    private javax.swing.JLabel textoCategoriaProducto;
    private javax.swing.JLabel textoCodigoCombo;
    private javax.swing.JLabel textoCodigoProducto;
    private javax.swing.JLabel textoComboAgregar;
    private javax.swing.JLabel textoDniEmpleado;
    private javax.swing.JLabel textoNombreCombo;
    private javax.swing.JLabel textoNombreProducto;
    private javax.swing.JLabel textoNombresEmpleado;
    private javax.swing.JLabel textoPasswordEmpleado;
    private javax.swing.JLabel textoPrecioCombo;
    private javax.swing.JLabel textoPrecioProducto;
    private javax.swing.JLabel textoProductoAgregar;
    private javax.swing.JLabel textoRolEmpleado;
    private javax.swing.JLabel textoStockProducto;
    private javax.swing.JLabel tituloCombos;
    private javax.swing.JLabel tituloEmpleados;
    private javax.swing.JLabel tituloProductoCombo;
    private javax.swing.JLabel tituloProductos;
    private javax.swing.JLabel tituloReportes;
    private javax.swing.JLabel tituloResultado;
    // End of variables declaration//GEN-END:variables
}
