/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import avance.poo.*;
/**
 *
 * @author Mara Rivera
 */
public class VCajero extends javax.swing.JFrame {
    private GestionAdmin gestionAdmin;
    private GestionCajero gestionCajero;
    private Cajero cajero;
    private Pedido pedidoActual;
    /**
     * Creates new form VCajero
     */
    public VCajero() {
       initComponents();
       
       gestionAdmin = new GestionAdmin();
       gestionCajero = new GestionCajero(gestionAdmin);
       DatosPrueba.cargar(gestionAdmin, gestionCajero);

       Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(22222222);

       if (empleado instanceof Cajero) {
            cajero = (Cajero) empleado;
       }

       pedidoActual = null;

       prepararVentana();

       if (cajero != null) {
            textoCajero.setText("Cajero: " + cajero.getNombreCompleto());
       }

       areaResultado.setText("");
       
    }
    
    public VCajero(GestionAdmin gestionAdmin, GestionCajero gestionCajero, Cajero cajero) {
        initComponents();

        this.gestionAdmin = gestionAdmin;
        this.gestionCajero = gestionCajero;
        this.cajero = cajero;
        this.pedidoActual = null;

        prepararVentana();

        textoCajero.setText("Cajero: " + cajero.getNombreCompleto());
        areaResultado.setText("");
    }   
    
    private void prepararVentana() {
        setLocationRelativeTo(null);
        textoPedidoActual.setText("Pedido actual: ninguno");

        cajaNumeroPedido.setEditable(false);
        cajaPedidoEntrega.setEditable(false);
        cajaPedidoComprobante.setEditable(false);

        cajaDniRepartidor.setEditable(true);

        cajaRuc.setEditable(false);
        cajaRazonSocial.setEditable(false);

        cajaRuc.setText("");
        cajaRazonSocial.setText("");

        checkBoleta.setSelected(false);
        checkFactura.setSelected(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textoTipoDocumento = new javax.swing.JLabel();
        cajaTipoDocumento = new javax.swing.JTextField();
        textoDocumento = new javax.swing.JLabel();
        cajaDocumento = new javax.swing.JTextField();
        textoNombres = new javax.swing.JLabel();
        cajaNombres = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JLabel();
        cajaApellidos = new javax.swing.JTextField();
        textoDireccion = new javax.swing.JLabel();
        cajaDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JLabel();
        cajaTelefono = new javax.swing.JTextField();
        botonRegistrarCliente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        textoCajero = new javax.swing.JLabel();
        tituloPedido = new javax.swing.JLabel();
        textoTipoEntrega = new javax.swing.JLabel();
        textoDocumentoPedido = new javax.swing.JLabel();
        cajaDocumentoPedido = new javax.swing.JTextField();
        botonCrearPedido = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        textoNumeroPedido = new javax.swing.JLabel();
        botonBuscarCliente = new javax.swing.JButton();
        botonModificarCliente = new javax.swing.JButton();
        cajaNumeroPedido = new javax.swing.JTextField();
        textoCodigoItem = new javax.swing.JLabel();
        cajaCodigoItem = new javax.swing.JTextField();
        textoCantidad = new javax.swing.JLabel();
        cajaCantidad = new javax.swing.JTextField();
        botonAgregarItem = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        tituloEntrega = new javax.swing.JLabel();
        textoPedidoEntrega = new javax.swing.JLabel();
        cajaPedidoEntrega = new javax.swing.JTextField();
        textoDniRepartidor = new javax.swing.JLabel();
        cajaDniRepartidor = new javax.swing.JTextField();
        botonAsignarRepartidor = new javax.swing.JButton();
        botonCerrarRecojo = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        tituloComprobante = new javax.swing.JLabel();
        textoPedidoActual = new javax.swing.JLabel();
        textoPedidoComprobante = new javax.swing.JLabel();
        cajaPedidoComprobante = new javax.swing.JTextField();
        textoTipoComprobante = new javax.swing.JLabel();
        textoRuc = new javax.swing.JLabel();
        cajaRuc = new javax.swing.JTextField();
        textoRazonSocial = new javax.swing.JLabel();
        cajaRazonSocial = new javax.swing.JTextField();
        botonVerCuenta = new javax.swing.JButton();
        botonEmitirComprobante = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        jScrollPaneResultado = new javax.swing.JScrollPane();
        tituloResultado = new javax.swing.JLabel();
        checkDelivery = new javax.swing.JCheckBox();
        checkRecojo = new javax.swing.JCheckBox();
        botonCerrarSesion = new javax.swing.JButton();
        botonVerProductos = new javax.swing.JButton();
        botonVerCombos = new javax.swing.JButton();
        botonVerRepartidores = new javax.swing.JButton();
        checkFactura = new javax.swing.JCheckBox();
        checkBoleta = new javax.swing.JCheckBox();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Buen día cajero! :D");

        textoTipoDocumento.setText("Tipo de Documento (DNI o RUC):");

        cajaTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaTipoDocumentoActionPerformed(evt);
            }
        });

        textoDocumento.setText("Documento:");

        textoNombres.setText("Nombres: ");

        textoApellidos.setText("Apellidos:");

        textoDireccion.setText("Direccion:");

        cajaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDireccionActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Registra al cliente:");

        textoTelefono.setText("Telefono");

        botonRegistrarCliente.setText("REGISTRAR CLIENTE");
        botonRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarClienteActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        textoCajero.setText("Cajero:");

        tituloPedido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloPedido.setText("Crea el Pedido:");

        textoTipoEntrega.setText("Tipo entrega:");

        textoDocumentoPedido.setText("Documento cliente:");

        botonCrearPedido.setText("CREAR PEDIDO");
        botonCrearPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearPedidoActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Agregar producto o combo:");

        textoNumeroPedido.setText("Nro pedido:");

        botonBuscarCliente.setText("BUSCAR CLIENTE");
        botonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarClienteActionPerformed(evt);
            }
        });

        botonModificarCliente.setText("MODIFICAR CLIENTE");
        botonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarClienteActionPerformed(evt);
            }
        });

        textoCodigoItem.setText("Codigo del item:");

        textoCantidad.setText("Cantidad:");

        botonAgregarItem.setText("AGREGAR ITEM");
        botonAgregarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarItemActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tituloEntrega.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloEntrega.setText("Entrega o recojo");

        textoPedidoEntrega.setText("DNI DEL REPARTIDOR:");

        textoDniRepartidor.setText("Nro pedido:");

        botonAsignarRepartidor.setText("ASIGNAR REPARTIDOR");
        botonAsignarRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAsignarRepartidorActionPerformed(evt);
            }
        });

        botonCerrarRecojo.setText("CERRAR RECOJO");
        botonCerrarRecojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarRecojoActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tituloComprobante.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloComprobante.setText("Comprobante");

        textoPedidoActual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoPedidoActual.setText("Pedido actual:");

        textoPedidoComprobante.setText("Nro pedido:");

        textoTipoComprobante.setText("Tipo comprobante:");

        textoRuc.setText("RUC:");

        textoRazonSocial.setText("Razón social:");

        cajaRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaRazonSocialActionPerformed(evt);
            }
        });

        botonVerCuenta.setText("VER CUENTA");
        botonVerCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerCuentaActionPerformed(evt);
            }
        });

        botonEmitirComprobante.setText("EMITIR COMPROBANTE");
        botonEmitirComprobante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmitirComprobanteActionPerformed(evt);
            }
        });

        areaResultado.setEditable(false);
        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        areaResultado.setAutoscrolls(false);
        jScrollPane1.setViewportView(areaResultado);

        tituloResultado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloResultado.setText("RESULTADO:");

        checkDelivery.setText("Delivery");
        checkDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDeliveryActionPerformed(evt);
            }
        });

        checkRecojo.setText("Recojo en tienda");
        checkRecojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRecojoActionPerformed(evt);
            }
        });

        botonCerrarSesion.setText("CERRAR SESIÓN");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        botonVerProductos.setText("VER PRODUCTOS DISPONIBLES");
        botonVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerProductosActionPerformed(evt);
            }
        });

        botonVerCombos.setText("VER COMBOS DISPONIBLES");
        botonVerCombos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerCombosActionPerformed(evt);
            }
        });

        botonVerRepartidores.setText("VER REPARTIDORES DISPONIBLES");
        botonVerRepartidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerRepartidoresActionPerformed(evt);
            }
        });

        checkFactura.setText("Factura");
        checkFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFacturaActionPerformed(evt);
            }
        });

        checkBoleta.setText("Boleta");
        checkBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(cajaCodigoItem, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(textoCodigoItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                                            .addComponent(textoNumeroPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(cajaNumeroPedido, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addGap(40, 40, 40)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(textoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cajaCantidad)
                                                            .addComponent(botonAgregarItem, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                                                    .addComponent(botonVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(botonVerCombos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(43, 43, 43)
                                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(106, 106, 106)
                                                .addComponent(jLabel4))
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cajaPedidoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(textoDniRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cajaDniRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(botonCerrarRecojo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(botonAsignarRepartidor)))
                                            .addComponent(textoPedidoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(botonVerRepartidores, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(422, 422, 422)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(56, 56, 56)
                                                    .addComponent(tituloPedido))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(textoDocumentoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cajaDocumentoPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(59, 59, 59)
                                                    .addComponent(botonCrearPedido))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(textoPedidoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(12, 12, 12))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(18, 18, 18)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(checkDelivery)
                                                        .addComponent(textoTipoEntrega)
                                                        .addComponent(checkRecojo))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tituloEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(tituloComprobante))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cajaPedidoComprobante)
                                            .addComponent(textoPedidoComprobante, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                            .addComponent(textoRuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cajaRuc))
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(textoTipoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(textoRazonSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                    .addComponent(cajaRazonSocial)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(checkFactura)
                                                .addGap(18, 18, 18)
                                                .addComponent(checkBoleta))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(botonVerCuenta)
                                        .addGap(75, 75, 75)
                                        .addComponent(botonEmitirComprobante))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(tituloResultado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(botonCerrarSesion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel3))
                            .addComponent(textoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textoNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(114, 114, 114)
                                .addComponent(textoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textoTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(textoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cajaNombres)
                                    .addComponent(cajaTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(cajaDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cajaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(cajaDireccion)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonBuscarCliente)
                                    .addComponent(botonRegistrarCliente)
                                    .addComponent(botonModificarCliente))
                                .addGap(37, 37, 37)))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoCajero)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoDocumento)
                            .addComponent(textoTipoDocumento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNombres)
                            .addComponent(textoApellidos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(textoDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoTelefono)
                            .addComponent(botonRegistrarCliente))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cajaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonBuscarCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarCliente)
                        .addGap(24, 24, 24)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textoNumeroPedido)
                                    .addComponent(textoCantidad))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cajaNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(textoCodigoItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cajaCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonAgregarItem))
                                .addGap(26, 26, 26)
                                .addComponent(botonVerProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonVerCombos))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cajaPedidoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textoPedidoEntrega)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cajaDniRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonAsignarRepartidor)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(botonCerrarRecojo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonVerRepartidores))
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(botonCerrarSesion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tituloPedido)
                                        .addGap(26, 26, 26)
                                        .addComponent(textoDocumentoPedido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cajaDocumentoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textoTipoEntrega)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkDelivery)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkRecojo)
                                        .addGap(10, 10, 10)
                                        .addComponent(botonCrearPedido)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoPedidoActual))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tituloComprobante)
                                        .addGap(18, 18, 18)
                                        .addComponent(textoTipoComprobante)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(checkFactura)
                                            .addComponent(checkBoleta))
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoRuc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cajaRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(textoRazonSocial)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cajaRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(botonVerCuenta)
                                            .addComponent(botonEmitirComprobante))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tituloResultado)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(textoPedidoComprobante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaPedidoComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloEntrega)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoDniRepartidor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDireccionActionPerformed

    private void botonRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarClienteActionPerformed
        // TODO add your handling code here:
        String tipoDocumento = cajaTipoDocumento.getText();
        String documento = cajaDocumento.getText();
        String nombres = cajaNombres.getText();
        String apellidos = cajaApellidos.getText();
        String direccion = cajaDireccion.getText();
        String telefono = cajaTelefono.getText();

        if (tipoDocumento.equals("") || documento.equals("") || nombres.equals("") || apellidos.equals("")) {
            areaResultado.setText("Complete tipo de documento, documento, nombres y apellidos.");
        } else {
            Cliente cliente = gestionCajero.buscarClientePorDocumento(documento);

            if (cliente != null) {
                areaResultado.setText("El cliente ya esta registrado.");
            } else {
                cajero.registrarCliente(tipoDocumento, documento, nombres, apellidos, direccion, telefono);

                Cliente nuevoCliente = gestionCajero.buscarClientePorDocumento(documento);

                areaResultado.setText("Cliente registrado correctamente.\n\n"
                        + nuevoCliente.mostrarDatos());
            }
        }
    }//GEN-LAST:event_botonRegistrarClienteActionPerformed

    private void botonCrearPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearPedidoActionPerformed
        // TODO add your handling code here:
        String documentoCliente = cajaDocumentoPedido.getText();
        String tipoEntrega = "";

        if (checkDelivery.isSelected() && checkRecojo.isSelected()) {
            areaResultado.setText("Seleccione solo un tipo de entrega.");
        } else if (!checkDelivery.isSelected() && !checkRecojo.isSelected()) {
            areaResultado.setText("Seleccione un tipo de entrega.");
        } else if (documentoCliente.equals("")) {
            areaResultado.setText("Ingrese el documento del cliente.");
        } else {
            if (checkDelivery.isSelected()) {
                tipoEntrega = "Delivery";
            } else {
                tipoEntrega = "Recojo en Tienda";
            }

            Cliente cliente = gestionCajero.buscarClientePorDocumento(documentoCliente);

            if (cliente == null) {
                areaResultado.setText("No se puede crear el pedido porque el cliente no existe.");
            } else {
                pedidoActual = cajero.crearPedido(documentoCliente, tipoEntrega);

                textoPedidoActual.setText("Pedido actual: " + pedidoActual.getNumeroCorrelativo());

                cajaNumeroPedido.setText(pedidoActual.getNumeroCorrelativo() + "");
                cajaPedidoEntrega.setText(pedidoActual.getNumeroCorrelativo() + "");
                cajaPedidoComprobante.setText(pedidoActual.getNumeroCorrelativo() + "");

                cajaDniRepartidor.setText("");

                areaResultado.setText("Pedido creado correctamente.\n"
                        + "Numero de pedido: " + pedidoActual.getNumeroCorrelativo() + "\n"
                        + "Cliente: " + pedidoActual.getCliente().getNombreCompleto() + "\n"
                        + "Tipo entrega: " + pedidoActual.getTipoEntrega() + "\n"
                        + "Estado: " + pedidoActual.getEstado());
            }
        }
    }//GEN-LAST:event_botonCrearPedidoActionPerformed

    private void botonAgregarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarItemActionPerformed
        // TODO add your handling code here:
        if (pedidoActual == null) {
        areaResultado.setText("Primero debe crear un pedido.");
        } else {
            String codigo = cajaCodigoItem.getText();
            String cantidadTexto = cajaCantidad.getText();
            int cantidad = 0;

            if (cantidadTexto.equals("1")) {
                cantidad = 1;
            } else if (cantidadTexto.equals("2")) {
                cantidad = 2;
            } else if (cantidadTexto.equals("3")) {
                cantidad = 3;
            } else if (cantidadTexto.equals("4")) {
                cantidad = 4;
            } else if (cantidadTexto.equals("5")) {
                cantidad = 5;
            } else if (cantidadTexto.equals("6")) {
                cantidad = 6;
            } else if (cantidadTexto.equals("7")) {
                cantidad = 7;
            } else if (cantidadTexto.equals("8")) {
                cantidad = 8;
            } else if (cantidadTexto.equals("9")) {
                cantidad = 9;
            } else if (cantidadTexto.equals("10")) {
                cantidad = 10;
            }

            if (codigo.equals("")) {
                areaResultado.setText("Ingrese el codigo del item.");
            } else if (cantidad == 0) {
                areaResultado.setText("Ingrese una cantidad del 1 al 10.");
            } else {
                ItemMenu item = gestionAdmin.buscarItemMenu(codigo);

                if (item == null) {
                    areaResultado.setText("No existe producto o combo con ese codigo.");
                } else if (!item.hayStock(cantidad)) {
                    areaResultado.setText("No hay stock suficiente para ese item.");
                } else {
                    cajero.agregarItemAPedido(pedidoActual.getNumeroCorrelativo(), codigo, cantidad);

                    areaResultado.setText("Item agregado correctamente.\n"
                            + "Item: " + item.getNombre() + "\n"
                            + "Cantidad: " + cantidad + "\n\n"
                            + pedidoActual.generarDetalleCuenta());
                }
            }
        }
    }//GEN-LAST:event_botonAgregarItemActionPerformed

    private void botonAsignarRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAsignarRepartidorActionPerformed
        // TODO add your handling code here:
        if (pedidoActual == null) {
        areaResultado.setText("Primero debe crear un pedido.");

    } else if (!pedidoActual.getTipoEntrega().equals("Delivery")) {
        areaResultado.setText("Solo se asigna repartidor cuando el pedido es Delivery.");

    } else {
        String dni = cajaDniRepartidor.getText();
        Repartidor repartidor = null;

        for (int i = 0; i < gestionAdmin.getContadorEmpleados(); i++) {
            Empleado empleado = gestionAdmin.getListaEmpleados()[i];

            if ((empleado.getDni() + "").equals(dni) && empleado instanceof Repartidor) {
                repartidor = (Repartidor) empleado;
            }
        }

        if (dni.equals("")) {
            areaResultado.setText("Ingrese el DNI del repartidor.");

        } else if (repartidor == null) {
            areaResultado.setText("Repartidor no encontrado.");

        } else {
            cajero.asignarRepartidor(pedidoActual.getNumeroCorrelativo(), repartidor.getDni());

            areaResultado.setText("Repartidor asignado correctamente.\n"
                    + "Pedido: " + pedidoActual.getNumeroCorrelativo() + "\n"
                    + "Repartidor: " + repartidor.getNombreCompleto() + "\n"
                    + "Estado: " + pedidoActual.getEstado());
        }
    }
    }//GEN-LAST:event_botonAsignarRepartidorActionPerformed

    private void botonEmitirComprobanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmitirComprobanteActionPerformed
        // TODO add your handling code here:
        if (pedidoActual == null) {
        areaResultado.setText("Primero debe crear un pedido.");

        } else if (!checkBoleta.isSelected() && !checkFactura.isSelected()) {
            areaResultado.setText("Seleccione Boleta o Factura.");

        } else {
            String tipoComprobante = "";
            String ruc = cajaRuc.getText();
            String razonSocial = cajaRazonSocial.getText();

            if (checkBoleta.isSelected()) {
                tipoComprobante = "Boleta";
            } else {
                tipoComprobante = "Factura";
            }

            if (tipoComprobante.equals("Factura") && ruc.equals("")) {
                areaResultado.setText("Para factura debe ingresar RUC.");

            } else if (tipoComprobante.equals("Factura") && razonSocial.equals("")) {
                areaResultado.setText("Para factura debe ingresar razon social.");

            } else {
                pedidoActual.solicitarComprobante(tipoComprobante, ruc, razonSocial);

                String texto = "Comprobante solicitado correctamente.\n";
                texto = texto + "Pedido: " + pedidoActual.getNumeroCorrelativo() + "\n";
                texto = texto + "Tipo: " + tipoComprobante + "\n";

                if (tipoComprobante.equals("Factura")) {
                    texto = texto + "RUC: " + ruc + "\n";
                    texto = texto + "Razon social: " + razonSocial + "\n";
                }

                texto = texto + "\n";

                if (pedidoActual.getTipoEntrega().equals("Recojo en Tienda")) {
                    texto = texto + "La " + tipoComprobante + " se emitira cuando cierre el recojo.";
                } else {
                    texto = texto + "La " + tipoComprobante + " se emitira cuando el repartidor registre la entrega.";
                }

                areaResultado.setText(texto);
            }
        }
    }//GEN-LAST:event_botonEmitirComprobanteActionPerformed

    private void botonVerCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerCuentaActionPerformed
        // TODO add your handling code here:
        if (pedidoActual == null) {
            areaResultado.setText("Primero debe crear un pedido.");
        } else {
            areaResultado.setText(pedidoActual.generarDetalleCuenta());
        }
    }//GEN-LAST:event_botonVerCuentaActionPerformed

    private void botonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarClienteActionPerformed
        // TODO add your handling code here:
        String documento = cajaDocumento.getText();

        if (documento.equals("")) {
            areaResultado.setText("Ingrese el documento del cliente.");
        } else {
            Cliente cliente = gestionCajero.buscarClientePorDocumento(documento);

            if (cliente == null) {
                areaResultado.setText("Cliente no encontrado.");
            } else {
                cajaTipoDocumento.setText(cliente.getTipoDocumento());
                cajaDocumento.setText(cliente.getDocumento());
                cajaNombres.setText(cliente.getNombres());
                cajaApellidos.setText(cliente.getApellidos());
                cajaDireccion.setText(cliente.getDireccionEntrega());
                cajaTelefono.setText(cliente.getTelefono());

                areaResultado.setText("Cliente encontrado:\n\n" + cliente.mostrarDatos());
            }
        }
    }//GEN-LAST:event_botonBuscarClienteActionPerformed

    private void botonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarClienteActionPerformed
        // TODO add your handling code here:
        String documento = cajaDocumento.getText();
        String nombres = cajaNombres.getText();
        String apellidos = cajaApellidos.getText();
        String direccion = cajaDireccion.getText();
        String telefono = cajaTelefono.getText();

        if (documento.equals("")) {
            areaResultado.setText("Ingrese el documento del cliente.");
        } else {
            Cliente cliente = gestionCajero.buscarClientePorDocumento(documento);

            if (cliente == null) {
                areaResultado.setText("No se puede modificar porque el cliente no existe.");
            } else {
                cajero.modificarCliente(documento, nombres, apellidos, direccion, telefono);

                cliente = gestionCajero.buscarClientePorDocumento(documento);

                areaResultado.setText("Cliente modificado correctamente.\n\n"
                        + cliente.mostrarDatos());
            }
        }
    }//GEN-LAST:event_botonModificarClienteActionPerformed

    private void botonCerrarRecojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarRecojoActionPerformed
        // TODO add your handling code here:
         if (pedidoActual == null) {
        areaResultado.setText("Primero debe crear un pedido.");

        } else if (!pedidoActual.getTipoEntrega().equals("Recojo en Tienda")) {
            areaResultado.setText("Solo puede cerrar recojo si el tipo de entrega es Recojo en Tienda.");

        } else {
            cajero.cerrarPedidoRecojo(pedidoActual.getNumeroCorrelativo());

            String texto = "Pedido cerrado como entregado.\n";
            texto = texto + "Pedido: " + pedidoActual.getNumeroCorrelativo() + "\n";
            texto = texto + "Estado: " + pedidoActual.getEstado() + "\n\n";

            if (pedidoActual.getTipoComprobanteSolicitado().equals("")) {
                texto = texto + pedidoActual.generarDetalleCuenta() + "\n\n";
                texto = texto + "No se solicito comprobante para este pedido.";

            } else {
                Comprobante comprobante = cajero.emitirComprobante(
                        pedidoActual.getNumeroCorrelativo(),
                        pedidoActual.getTipoComprobanteSolicitado(),
                        pedidoActual.getRucComprobante(),
                        pedidoActual.getRazonSocialComprobante()
                );

                if (comprobante == null) {
                    texto = texto + pedidoActual.generarDetalleCuenta() + "\n\n";
                    texto = texto + "No se pudo emitir el comprobante.";
                } else {
                    texto = texto + "COMPROBANTE EMITIDO\n\n";
                    texto = texto + comprobante.mostrarDatos();
                }
            }

            areaResultado.setText(texto);
        }
    }//GEN-LAST:event_botonCerrarRecojoActionPerformed

    private void checkDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDeliveryActionPerformed
        // TODO add your handling code here:
        if (checkDelivery.isSelected()) {
        checkRecojo.setSelected(false);
    }
    }//GEN-LAST:event_checkDeliveryActionPerformed

    private void checkRecojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRecojoActionPerformed
        // TODO add your handling code here:
        if (checkRecojo.isSelected()) {
        checkDelivery.setSelected(false);
    }
    }//GEN-LAST:event_checkRecojoActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
        VLogin ventana = new VLogin(gestionAdmin, gestionCajero);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    private void botonVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerProductosActionPerformed
        // TODO add your handling code here:
        String texto = "LISTA DE PRODUCTOS\n\n";

        for (int i = 0; i < gestionAdmin.getContadorProductos(); i++) {
            Producto producto = gestionAdmin.getListaProductos()[i];

            texto = texto + producto.mostrarDatos() + "\n";
        }

        areaResultado.setText(texto);
    }//GEN-LAST:event_botonVerProductosActionPerformed

    private void botonVerCombosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerCombosActionPerformed
        // TODO add your handling code here:
        String texto = "LISTA DE COMBOS\n\n";

        for (int i = 0; i < gestionAdmin.getContadorCombos(); i++) {
            Combo combo = gestionAdmin.getListaCombos()[i];

            texto = texto + combo.mostrarDatos() + "\n";
        }

        areaResultado.setText(texto);
    }//GEN-LAST:event_botonVerCombosActionPerformed

    private void botonVerRepartidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerRepartidoresActionPerformed
        // TODO add your handling code here:
        String texto = "REPARTIDORES DISPONIBLES\n\n";

        for (int i = 0; i < gestionAdmin.getContadorEmpleados(); i++) {
            Empleado empleado = gestionAdmin.getListaEmpleados()[i];

            if (empleado instanceof Repartidor) {
                Repartidor repartidor = (Repartidor) empleado;

                if (repartidor.isDisponible() && repartidor.isEstadoUnidad()) {
                    texto = texto + "DNI: " + repartidor.getDni() + "\n";
                    texto = texto + "Nombre: " + repartidor.getNombreCompleto() + "\n";
                    texto = texto + "Unidad: " + repartidor.getUnidadTransporte() + "\n";
                    texto = texto + "-----------------------------\n\n";
                }
            }
        }

        if (texto.equals("REPARTIDORES DISPONIBLES\n\n")) {
            texto = texto + "No hay repartidores disponibles.";
        }

        areaResultado.setText(texto);
    }//GEN-LAST:event_botonVerRepartidoresActionPerformed

    private void cajaTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaTipoDocumentoActionPerformed

    private void cajaRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaRazonSocialActionPerformed

    private void checkFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFacturaActionPerformed
        // TODO add your handling code here:
        if (checkFactura.isSelected()) {
            checkBoleta.setSelected(false);

            cajaRuc.setEditable(true);
            cajaRazonSocial.setEditable(true);
        }
    }//GEN-LAST:event_checkFacturaActionPerformed

    private void checkBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoletaActionPerformed
        // TODO add your handling code here:
        if (checkBoleta.isSelected()) {
            checkFactura.setSelected(false);

            cajaRuc.setText("");
            cajaRazonSocial.setText("");

            cajaRuc.setEditable(false);
            cajaRazonSocial.setEditable(false);
        }
    }//GEN-LAST:event_checkBoletaActionPerformed

    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton botonAgregarItem;
    private javax.swing.JButton botonAsignarRepartidor;
    private javax.swing.JButton botonBuscarCliente;
    private javax.swing.JButton botonCerrarRecojo;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonCrearPedido;
    private javax.swing.JButton botonEmitirComprobante;
    private javax.swing.JButton botonModificarCliente;
    private javax.swing.JButton botonRegistrarCliente;
    private javax.swing.JButton botonVerCombos;
    private javax.swing.JButton botonVerCuenta;
    private javax.swing.JButton botonVerProductos;
    private javax.swing.JButton botonVerRepartidores;
    private javax.swing.JTextField cajaApellidos;
    private javax.swing.JTextField cajaCantidad;
    private javax.swing.JTextField cajaCodigoItem;
    private javax.swing.JTextField cajaDireccion;
    private javax.swing.JTextField cajaDniRepartidor;
    private javax.swing.JTextField cajaDocumento;
    private javax.swing.JTextField cajaDocumentoPedido;
    private javax.swing.JTextField cajaNombres;
    private javax.swing.JTextField cajaNumeroPedido;
    private javax.swing.JTextField cajaPedidoComprobante;
    private javax.swing.JTextField cajaPedidoEntrega;
    private javax.swing.JTextField cajaRazonSocial;
    private javax.swing.JTextField cajaRuc;
    private javax.swing.JTextField cajaTelefono;
    private javax.swing.JTextField cajaTipoDocumento;
    private javax.swing.JCheckBox checkBoleta;
    private javax.swing.JCheckBox checkDelivery;
    private javax.swing.JCheckBox checkFactura;
    private javax.swing.JCheckBox checkRecojo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneResultado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel textoApellidos;
    private javax.swing.JLabel textoCajero;
    private javax.swing.JLabel textoCantidad;
    private javax.swing.JLabel textoCodigoItem;
    private javax.swing.JLabel textoDireccion;
    private javax.swing.JLabel textoDniRepartidor;
    private javax.swing.JLabel textoDocumento;
    private javax.swing.JLabel textoDocumentoPedido;
    private javax.swing.JLabel textoNombres;
    private javax.swing.JLabel textoNumeroPedido;
    private javax.swing.JLabel textoPedidoActual;
    private javax.swing.JLabel textoPedidoComprobante;
    private javax.swing.JLabel textoPedidoEntrega;
    private javax.swing.JLabel textoRazonSocial;
    private javax.swing.JLabel textoRuc;
    private javax.swing.JLabel textoTelefono;
    private javax.swing.JLabel textoTipoComprobante;
    private javax.swing.JLabel textoTipoDocumento;
    private javax.swing.JLabel textoTipoEntrega;
    private javax.swing.JLabel tituloComprobante;
    private javax.swing.JLabel tituloEntrega;
    private javax.swing.JLabel tituloPedido;
    private javax.swing.JLabel tituloResultado;
    // End of variables declaration//GEN-END:variables
}
