/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import avance.poo.*;
/**
 *
 * @author Tyra Rivera
 */
public class VLogin extends javax.swing.JFrame {
    private GestionAdmin gestionAdmin;
    private GestionCajero gestionCajero;
    /**
     * Creates new form VLogin
     */
    public VLogin() {
        initComponents();

        gestionAdmin = new GestionAdmin();
        gestionCajero = new GestionCajero(gestionAdmin);
        DatosPrueba.cargar(gestionAdmin, gestionCajero);

        setLocationRelativeTo(null);
        cajaDni.setText("");
        cajaContrasena.setText("");
        textoVentana.setText("LOGIN");
    }
    public VLogin(GestionAdmin gestionAdmin, GestionCajero gestionCajero) {
        initComponents();

        this.gestionAdmin = gestionAdmin;
        this.gestionCajero = gestionCajero;

        setLocationRelativeTo(null);
        cajaDni.setText("");
        cajaContrasena.setText("");
        textoVentana.setText("LOGIN");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textoDni = new javax.swing.JLabel();
        cajaDni = new javax.swing.JTextField();
        textoContrasena = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        cajaContrasena = new javax.swing.JPasswordField();
        textoVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SISTEMA DE RESTAURANTE");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 9)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Usuarios disponibles:\nAdministrador: 11111111 / admin123\nCajero: 22222222 / cajero123\nRepartidor: 33333333 / repartidor123");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        textoDni.setText("DNI:");

        cajaDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaDniActionPerformed(evt);
            }
        });

        textoContrasena.setText("CONTRASEÑA:");

        botonIngresar.setText("INGRESAR");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        cajaContrasena.setText("jPasswordField1");
        cajaContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaContrasenaActionPerformed(evt);
            }
        });

        textoVentana.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoVentana.setText("LOGIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cajaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(botonIngresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(textoContrasena))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoVentana)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textoDni)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoVentana)
                        .addGap(27, 27, 27)
                        .addComponent(textoDni)
                        .addGap(18, 18, 18)))
                .addComponent(cajaDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cajaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonIngresar)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaDniActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
        String dni = cajaDni.getText();
        String contrasena = cajaContrasena.getText();

        if (dni.equals("")) {
            textoVentana.setText("Ingrese el DNI");
        } else if (contrasena.equals("")) {
            textoVentana.setText("Ingrese contraseña");
        } else {
            Empleado empleado = null;

        for (int i = 0; i < gestionAdmin.getContadorEmpleados(); i++) {
            Empleado actual = gestionAdmin.getListaEmpleados()[i];

            if ((actual.getDni() + "").equals(dni) && actual.autenticar(contrasena)) {
                empleado = actual;
            }
        }

        if (empleado == null) {
            textoVentana.setText("Usuario incorrecto");
            cajaContrasena.setText("");
        } else {
            if (empleado instanceof Administrador) {
                VAdministrador ventana = new VAdministrador(gestionAdmin, gestionCajero, (Administrador) empleado);
                ventana.setVisible(true);
                this.setVisible(false);

            } else if (empleado instanceof Cajero) {
                VCajero ventana = new VCajero(gestionAdmin, gestionCajero, (Cajero) empleado);
                ventana.setVisible(true);
                this.setVisible(false);
            } else if (empleado instanceof Repartidor) {
                VRepartidor ventana = new VRepartidor(gestionAdmin, gestionCajero, (Repartidor) empleado);
                ventana.setVisible(true);
                this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void cajaContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaContrasenaActionPerformed
                                              

                                                                     

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPasswordField cajaContrasena;
    private javax.swing.JTextField cajaDni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel textoContrasena;
    private javax.swing.JLabel textoDni;
    private javax.swing.JLabel textoVentana;
    // End of variables declaration//GEN-END:variables
}
