/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import avance.poo.*;
/**
 *
 * @author Mara Rivera
 */
public class VRepartidor extends javax.swing.JFrame {
    private GestionAdmin gestionAdmin;
    private GestionCajero gestionCajero;
    private Repartidor repartidor;
    /**
     * Creates new form VRepartidor
     */
    public VRepartidor() {
        initComponents();
        gestionAdmin = new GestionAdmin();
        gestionCajero = new GestionCajero(gestionAdmin);
        DatosPrueba.cargar(gestionAdmin, gestionCajero);

        Empleado empleado = gestionAdmin.buscarEmpleadoPorDni(33333333);

        if (empleado instanceof Repartidor) {
            repartidor = (Repartidor) empleado;
        }

        prepararVentana();

        if (repartidor != null) {
            textoRepartidor.setText("Repartidor: " + repartidor.getNombreCompleto());
            cajaUnidadTransporte.setText(repartidor.getUnidadTransporte());
            checkUnidadOperativa.setSelected(repartidor.isEstadoUnidad());

            if (repartidor.isDisponible()) {
                textoEstado.setText("Estado: Disponible");
            } else {
                textoEstado.setText("Estado: Ocupado");
            }
        }

        areaResultado.setText("");
    }
    public VRepartidor(GestionAdmin gestionAdmin, GestionCajero gestionCajero, Repartidor repartidor) {
        initComponents();

        this.gestionAdmin = gestionAdmin;
        this.gestionCajero = gestionCajero;
        this.repartidor = repartidor;

        prepararVentana();

        textoRepartidor.setText("Repartidor: " + repartidor.getNombreCompleto());
        cajaUnidadTransporte.setText(repartidor.getUnidadTransporte());
        checkUnidadOperativa.setSelected(repartidor.isEstadoUnidad());

        if (repartidor.isDisponible()) {
            textoEstado.setText("Estado: Disponible");
        } else {
            textoEstado.setText("Estado: Ocupado");
        }

        areaResultado.setText("");
    }
    
    private void prepararVentana() {
        setLocationRelativeTo(null);
        areaResultado.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        tituloRepartidor = new javax.swing.JLabel();
        textoRepartidor = new javax.swing.JLabel();
        textoEstado = new javax.swing.JLabel();
        textoUnidad = new javax.swing.JLabel();
        checkUnidadOperativa = new javax.swing.JCheckBox();
        cajaUnidadTransporte = new javax.swing.JTextField();
        botonGuardarUnidad = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        botonVerPedidos = new javax.swing.JButton();
        textoNumeroPedido = new javax.swing.JLabel();
        cajaNumeroPedido = new javax.swing.JTextField();
        botonRegistrarEntrega = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        subtituloDatosUnidad = new javax.swing.JLabel();
        subtituloPedidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textoIncidente = new javax.swing.JLabel();
        cajaIncidente = new javax.swing.JTextField();
        botonReportarIncidente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cajaRecargo = new javax.swing.JTextField();
        botonReportarRecargo = new javax.swing.JButton();
        tituloareaResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaResultado = new javax.swing.JTextArea();
        jScrollPaneResultado = new javax.swing.JProgressBar();
        botonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloRepartidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tituloRepartidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRepartidor.setText("Buen día repartidor!");

        textoRepartidor.setText("Repartidor:");

        textoEstado.setText("Estado:");

        textoUnidad.setText("Unidad:");

        checkUnidadOperativa.setText("Unidad Operativa?");

        botonGuardarUnidad.setText("GUARDAR UNIDAD");
        botonGuardarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarUnidadActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        botonVerPedidos.setText("VER PEDIDOS ASIGNADOS");
        botonVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPedidosActionPerformed(evt);
            }
        });

        textoNumeroPedido.setText("Número del pedido:");

        botonRegistrarEntrega.setText("REGISTRAR ENTREGA");
        botonRegistrarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarEntregaActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        subtituloDatosUnidad.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        subtituloDatosUnidad.setText("Datos de la Unidad:");

        subtituloPedidos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        subtituloPedidos.setText("Pedidos:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Incidentes:");

        textoIncidente.setText("Incidente:");

        botonReportarIncidente.setText("REPORTAR INCIDENTE");
        botonReportarIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportarIncidenteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Recargo:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("Recargo:");

        botonReportarRecargo.setText("REPORTAR RECARGO");
        botonReportarRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReportarRecargoActionPerformed(evt);
            }
        });

        tituloareaResultado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloareaResultado.setText("Resultado:");

        areaResultado.setColumns(20);
        areaResultado.setRows(5);
        jScrollPane1.setViewportView(areaResultado);

        botonCerrarSesion.setText("CERRAR SESIÓN");
        botonCerrarSesion.setToolTipText("");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkUnidadOperativa)
                                    .addComponent(textoEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoUnidad)
                                        .addGap(27, 27, 27)
                                        .addComponent(cajaUnidadTransporte))
                                    .addComponent(botonGuardarUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(subtituloDatosUnidad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonVerPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textoNumeroPedido)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cajaNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(botonRegistrarEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(subtituloPedidos)
                                .addGap(93, 93, 93)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(botonReportarIncidente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(textoIncidente, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cajaIncidente, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(92, 92, 92))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(botonReportarRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(cajaRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(16, 16, 16)))
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(tituloareaResultado))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloRepartidor)
                    .addComponent(botonCerrarSesion))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoRepartidor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoEstado)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(subtituloDatosUnidad)
                                    .addComponent(subtituloPedidos))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonVerPedidos)
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textoNumeroPedido)
                                            .addComponent(cajaNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonRegistrarEntrega))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(textoUnidad)
                                            .addComponent(cajaUnidadTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(checkUnidadOperativa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonGuardarUnidad))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoIncidente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cajaIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonReportarIncidente)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cajaRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonReportarRecargo)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator3)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloareaResultado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPaneResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarUnidadActionPerformed
        // TODO add your handling code here:
        String unidad = cajaUnidadTransporte.getText();

        if (unidad.equals("")) {
            areaResultado.setText("Ingrese la unidad de transporte.");
        } else {
            repartidor.setUnidadTransporte(unidad);
            repartidor.setEstadoUnidad(checkUnidadOperativa.isSelected());

            areaResultado.setText("Datos de unidad actualizados.\n"
                    + "Unidad: " + repartidor.getUnidadTransporte() + "\n"
                    + "Unidad operativa: " + repartidor.isEstadoUnidad());
        }
    }//GEN-LAST:event_botonGuardarUnidadActionPerformed

    private void botonVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPedidosActionPerformed
        // TODO add your handling code here:
        String texto = "PEDIDOS ASIGNADOS\n\n";

        if (repartidor.getContadorPedidosAsignados() == 0) {
            texto = texto + "No tiene pedidos asignados.";
        } else {
            for (int i = 0; i < repartidor.getContadorPedidosAsignados(); i++) {
                Pedido pedido = repartidor.getPedidosAsignados()[i];

                texto = texto + "Pedido: " + pedido.getNumeroCorrelativo() + "\n"
                        + "Cliente: " + pedido.getCliente().getNombreCompleto() + "\n"
                        + "Tipo entrega: " + pedido.getTipoEntrega() + "\n"
                        + "Estado: " + pedido.getEstado() + "\n"
                        + "Total: S/" + pedido.calcularTotal() + "\n\n";
            }
        }

        areaResultado.setText(texto);
    }//GEN-LAST:event_botonVerPedidosActionPerformed

    private void botonRegistrarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarEntregaActionPerformed
        // TODO add your handling code here:
        String numeroTexto = cajaNumeroPedido.getText();

    if (numeroTexto.equals("")) {
        areaResultado.setText("Ingrese el numero de pedido.");
    } else {
        int numeroPedido = 0;

        for (int i = 0; i < numeroTexto.length(); i++) {
            numeroPedido = numeroPedido * 10 + (numeroTexto.charAt(i) - '0');
        }

        Pedido pedido = repartidor.buscarPedidoPorNumero(numeroPedido);

        if (pedido == null) {
            areaResultado.setText("Pedido no encontrado en sus pedidos asignados.");

        } else if (!pedido.getEstado().equals("En Camino")) {
            areaResultado.setText("El pedido no esta en camino.");

        } else {
            repartidor.registrarEntrega(numeroPedido);

            textoEstado.setText("Estado: Disponible");

            String texto = "Entrega registrada correctamente.\n";
            texto = texto + "Pedido: " + numeroPedido + "\n";
            texto = texto + "Estado actual: " + pedido.getEstado() + "\n";
            texto = texto + "Repartidor: " + repartidor.getNombreCompleto() + "\n\n";

            if (pedido.getTipoComprobanteSolicitado().equals("")) {
                texto = texto + "No se solicito comprobante para este pedido.";
            } else {
                Comprobante comprobante = gestionCajero.emitirComprobante(
                        numeroPedido,
                        pedido.getTipoComprobanteSolicitado(),
                        pedido.getRucComprobante(),
                        pedido.getRazonSocialComprobante()
                );

                if (comprobante == null) {
                    texto = texto + "No se pudo emitir el comprobante.";
                } else {
                    texto = texto + "COMPROBANTE EMITIDO\n\n";
                    texto = texto + comprobante.mostrarDatos();
                }
            }

            areaResultado.setText(texto);
        }
    }
    }//GEN-LAST:event_botonRegistrarEntregaActionPerformed

    private void botonReportarIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportarIncidenteActionPerformed
        // TODO add your handling code here:
        String numeroTexto = cajaNumeroPedido.getText();
        String incidente = cajaIncidente.getText();

        if (numeroTexto.equals("")) {
            areaResultado.setText("Ingrese el numero de pedido.");
        } else if (incidente.equals("")) {
            areaResultado.setText("Ingrese la descripcion del incidente.");
        } else {
            int numeroPedido = 0;

            for (int i = 0; i < numeroTexto.length(); i++) {
                numeroPedido = numeroPedido * 10 + (numeroTexto.charAt(i) - '0');
            }

            Pedido pedido = repartidor.buscarPedidoPorNumero(numeroPedido);

            if (pedido == null) {
                areaResultado.setText("Pedido no encontrado en sus pedidos asignados.");
            } else {
                repartidor.reportarIncidente(numeroPedido, incidente);

                areaResultado.setText("Incidente registrado correctamente.\n"
                        + "El pedido aun NO ha sido entregado.\n\n"
                        + pedido.generarDetalleCuenta());
            }
        }
    }//GEN-LAST:event_botonReportarIncidenteActionPerformed

    private void botonReportarRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReportarRecargoActionPerformed
        // TODO add your handling code here:
        String numeroTexto = cajaNumeroPedido.getText();
        String recargoTexto = cajaRecargo.getText();

        if (numeroTexto.equals("")) {
            areaResultado.setText("Ingrese el numero de pedido.");
        } else if (recargoTexto.equals("")) {
            areaResultado.setText("Ingrese el recargo.");
        } else {
            int numeroPedido = 0;
            int recargo = 0;

            for (int i = 0; i < numeroTexto.length(); i++) {
                numeroPedido = numeroPedido * 10 + (numeroTexto.charAt(i) - '0');
            }

            for (int i = 0; i < recargoTexto.length(); i++) {
                recargo = recargo * 10 + (recargoTexto.charAt(i) - '0');
            }

            Pedido pedido = repartidor.buscarPedidoPorNumero(numeroPedido);

            if (pedido == null) {
                areaResultado.setText("Pedido no encontrado en sus pedidos asignados.");
            } else {
                repartidor.reportarRecargo(numeroPedido, recargo);

                areaResultado.setText("Recargo registrado correctamente.\n"
                        + "El pedido aun NO ha sido entregado.\n\n"
                        + pedido.generarDetalleCuenta());
            }
        }
    }//GEN-LAST:event_botonReportarRecargoActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        // TODO add your handling code here:
        VLogin ventana = new VLogin(gestionAdmin, gestionCajero);
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRepartidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRepartidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaResultado;
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonGuardarUnidad;
    private javax.swing.JButton botonRegistrarEntrega;
    private javax.swing.JButton botonReportarIncidente;
    private javax.swing.JButton botonReportarRecargo;
    private javax.swing.JButton botonVerPedidos;
    private javax.swing.JTextField cajaIncidente;
    private javax.swing.JTextField cajaNumeroPedido;
    private javax.swing.JTextField cajaRecargo;
    private javax.swing.JTextField cajaUnidadTransporte;
    private javax.swing.JCheckBox checkUnidadOperativa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar jScrollPaneResultado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel subtituloDatosUnidad;
    private javax.swing.JLabel subtituloPedidos;
    private javax.swing.JLabel textoEstado;
    private javax.swing.JLabel textoIncidente;
    private javax.swing.JLabel textoNumeroPedido;
    private javax.swing.JLabel textoRepartidor;
    private javax.swing.JLabel textoUnidad;
    private javax.swing.JLabel tituloRepartidor;
    private javax.swing.JLabel tituloareaResultado;
    // End of variables declaration//GEN-END:variables
}
